# This file is part of libbot2.
#
# libbot2 is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# libbot2 is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
# License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with libbot2. If not, see <https://www.gnu.org/licenses/>.

---
name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

  push:
    branches:
      - drake

jobs:
  macos:
    name: macOS Latest
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install prerequisites
        run: ./scripts/setup/mac/install_prereqs
        shell: zsh -f {0}
      - name: Build and install
        run: |
          mkdir build
          pushd build
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_FLAGS=-DGL_SILENCE_DEPRECATION=1 \
            -DCMAKE_CXX_FLAGS=-DGL_SILENCE_DEPRECATION=1 \
            -DPYTHON_EXECUTABLE=/usr/local/bin/python3 \
            -DWITH_BOT_VIS=OFF \
            ..
          make install
          popd
        shell: zsh -f {0}

  ubuntu:
    name: Ubuntu Latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install prerequisites
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo -E apt-get update -qq
          sudo -E apt-get autoremove -qq
          export APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1
          sudo -E ./scripts/setup/linux/ubuntu/bionic/install_prereqs
      - name: Download, build, and install LCM
        run: |
          wget -nv https://github.com/lcm-proj/lcm/archive/v1.4.0.tar.gz
          tar -xf v1.4.0.tar.gz
          rm -f v1.4.0.tar.gz
          pushd lcm-1.4.0
          mkdir build
          pushd build
          /usr/bin/cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_FLAGS=-w \
            -DCMAKE_CXX_FLAGS=-w \
            -DCMAKE_INSTALL_PREFIX=/opt/lcm \
            -DLCM_ENABLE_EXAMPLES=OFF \
            -DLCM_ENABLE_GO=OFF \
            -DLCM_ENABLE_LUA=OFF \
            -DLCM_ENABLE_TESTS=OFF \
            -DLCM_INSTALL_M4MACROS=OFF \
            -DLCM_INSTALL_PKGCONFIG=OFF \
            -DPYTHON_EXECUTABLE=/usr/bin/python3 \
            ..
          make
          sudo make install
          popd
          popd
          rm -rf lcm-1.4.0
      - name: Build and install
        run: |
          mkdir build
          pushd build
          /usr/bin/cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_SYSTEM_PREFIX_PATH=/opt/lcm \
            -DPYTHON_EXECUTABLE=/usr/bin/python3 \
            ..
          make install
          popd
